syntax enable

set tabstop=2     " Display tab as two spaces
set expandtab     " Insert spaces instead of tab symbol
set softtabstop=2 " The number of spaces to insert
set shiftwidth=2  " Indent size

set number " Line numbering

so ~/.dotfiles/vim/vundlesetup.vim

" highlight line 81
set textwidth=80
set colorcolumn=+1

" key maps

" copy and paste
vmap <C-c> "+yi
vmap <C-x> "+c
vmap <C-v> c<ESC>"+p
imap <C-v> <ESC>"+pa

" Tagbar
nmap <F8> :TagbarToggle<CR>
nmap <F7> :NERDTreeToggle<CR>

" pywal colors
colorscheme wal

" airline to use powerline fonts
let g:airline_powerline_fonts = 1

" Unicode support
set encoding=utf-8

" Whitespaces
set list listchars=tab:→\ ,trail:·
set list
